### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ROODAY** [ROODAY/SMMRY-Client#1]
- [x] text-align center on lines input
- [x] text-area have same dark background and white text for consistency (same goes for lines input)
- [x] make button default background state transparent (and only fill if not disabled, make border grey if disabled)
- [x] add firebase login to authenticate users. store api key in firebase and use it upon requests. if someone doesnt have an api key, prompt them to go get one. Have a small tab at the top, like an arrow or smth, to pull down the login thing
- [x] move to DO and use PM2 to run it, have caddy use the proper domain
- [x] remove the webvitals stuff and prune unused dependencies
- [x] use a more pleasant font, perhaps increase font-size (open sans)
- [x] add this ```h1::after {
    content: "client";
    font-size: 1rem;
    vertical-align: top;
    position: absolute;
}```
- [x] TTS reading option
- [x] Change bookmarklet to be just one that tries both (if one fails use the other) and then open the client automatically. Check how smmry does their bookmarklet (redirects to site with URL of article as path). Add custom case for wired
- [x] make default lines 10
- [x] copy smmry textarea placeholder
- [ ] dark mode toggle (whats the most lightweight way of doing this)
- [x] If user tries to smmrz without logging in, swal to tell them to login and save an API key first
- [x] Make mobile friendly
- [ ] Add re-smmrz button to redo with new line number (just take back to previous page without wiping any data)
